markdown: kramdown
highlighter: rouge
permalink: /posts/:title.html
exclude: ["README.md"]
excerpt_separator: "<!-- more -->"

github: Tsinghua-gongjing
author: "龚警"
email: gonj15@mails.tsinghua.edu.cn
name: "Jing's blog"
all_categories: [
["genomics", "Genomics","/posts/genomics.html"], 
["python", "Python","/posts/python.html"], 
["linux", "Linux","/posts/linux.html"],
["visualization", "Visualization","/posts/visualization.html"], 
["statistics", "Statistics", "/posts/statistics.html"],
["machinelearning", "MachineLearning", "/posts/machinelearning.html"],
["read", "Reading","/posts/read.html"], 
["other", "Other","/posts/other.html"],
["about", "About","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

kramdown:
  input: GFM
  syntax_highlighter: rouge

disqus:
    shortname: https-tsinghua-gongjing-github-io
    # the short name is website's rather than accounts

# improved code highlighter: https://demisx.github.io/jekyll/2014/01/13/improve-code-highlighting-in-jekyll.html
# syntax: https://gist.github.com/demisx/8408522
