markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
exclude: ["README.md"]
excerpt_separator: "<!-- more -->"

github: Tsinghua-gongjing
author: "龚警"
email: gonj15@mails.tsinghua.edu.cn
name: "龚警个人博客"
all_categories: [
["Python", "python编程","/posts/python.html"], 
["linux", "Linux相关","/posts/linux.html"],
["read", "读书笔记","/posts/read.html"], 
["other", "杂记","/posts/other.html"],
["about", "关于","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

