markdown: kramdown
highlighter: rouge
permalink: /posts/:title.html
exclude: ["README.md"]
excerpt_separator: "<!-- more -->"

github: Tsinghua-gongjing
author: "龚警"
email: gonj15@mails.tsinghua.edu.cn
name: "龚警个人博客"
all_categories: [
["genomics", "基因组学","/posts/genomics.html"], 
["python", "Python","/posts/python.html"], 
["linux", "Linux","/posts/linux.html"],
["visualization", "可视化","/posts/visualization.html"], 
["read", "读书笔记","/posts/read.html"], 
["other", "杂记","/posts/other.html"],
["about", "关于","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

kramdown:
  input: GFM
  syntax_highlighter: rouge

disqus:
    shortname: https-tsinghua-gongjing-github-io
    # the short name is website's rather than accounts
